name: Publish release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      upload:
        description: 'Upload release to PyPI'
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  build:
    name: Build the release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: "latest"

      - name: Install the project
        run: uv sync --no-group dev

      - name: Package project
        run: uv build -o dist/

      - name: Sign build artifacts
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: "dist/*"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          retention-days: 1
          path: "dist/"

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    if: ${{ (github.event.inputs.upload || github.ref_type == 'tag') }}

    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: release-dists
          path: dist

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
